### ISSUE TITLE
replace context to activitiy

### ISSUE THREAD

**Issue by kaleai** [workarounds/bundler#12]
Annotation gen the function:

``` JAVA
public void start(Context context) {
      context.startActivity(intent(context));
}
```

I think the param should be limit to activity.

**Comment by williamwebb** [comment]
While not common there are situations to where you want to start an activity from something that is not an activity. Does it hurt anything to leave this option available?

**Comment by kaleai** [comment]
First I think your lib is very useful,I want to write a article to introduce it in my own blog.
When I use a context from dialog to start a activity,application will be crash.I think only activity could to start activity.
![68747470733a2f2f706963332e7a68696d672e636f6d2f65336633323336636264393663363963646561313064303134626163626561655f622e706e67](https://cloud.githubusercontent.com/assets/9552155/13847522/965a9702-ec88-11e5-9350-882304b8b212.png)

**Comment by williamwebb** [comment]
Unless something has changed very recently you can definitely start an activity from a Dialog, even a background Service. Like i said it's not common(and generally frowned upon), but it is possible.
