### ISSUE TITLE
Provide a way to avoid generate class Bundler

### ISSUE THREAD

**Issue by yjfnypeu** [workarounds/bundler#16]
Excuse me! Bundler is a very useful lib for Android. But now we are experiencing some problems，
we are ready to use plug-in development mode,and in this way,each plug-in will generate a similar class,and caused duplicate class found when pack apk...So,can you provide a way to avoid generate bundler?

**Comment by madki** [comment]
@yjfnypeu You can use `@OptionsForBundle` and provide a `packageName` so that different plugins generate the `*Bundler.class` at different places.

**Comment by yjfnypeu** [comment]
OK。thanks!and there are another suggest:All of class that should be injected with bundle must be defined Bundler.inject() at present,if can you provide a way to inject in a easy way just like ButterKnife.bind() with base class? @madki
