### ISSUE TITLE
Support for custom fields

### ISSUE THREAD

**Issue by madki** [workarounds/bundler#2]
Support annotating user defined fields with `@Arg` and `@State`. For example allow annotating a `Date` object with `Arg` and let the user specify a class to put and retrieve it from the bundle. Something like `ArgsBundler` in [FragmentArgs](https://github.com/sockeqwe/fragmentargs) library. This would allow support for annotating `List` and objects parcelled using `Parceler` library

**Comment by praveendath92** [comment]
Gson!

**Comment by madki** [comment]
Fixed in 4c26f16b2911f987fbd8b00077069cfb9727d62a. Added support for `Serializer`. Write a custom `Serializer` to support custom types.

@praveendath92 gson types can also be serialized using `Serializer` but you'll have to write one serializer for every type (defeats the point of using gson)
