### ISSUE TITLE
Build script dependency not found

### ISSUE THREAD

**Issue by praveendath92** [workarounds/bundler#7]
I'm using other repositories besides mavenCentral and in my case I get plugin not found error. The following fixed the issue however.

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}
```

Referred from [andrioid-apt repository][android-apt]

[android-apt]: https://bitbucket.org/hvisser/android-apt

**Comment by madki** [comment]
added to readme in 8c62399f0a8eb561bfdf796f6bfe46f615a62a6a
