### ISSUE TITLE
What about "freighter"?

### ISSUE THREAD

**Issue by Rainer-Lang** [workarounds/bundler#9]
Should we use bundler or freighter? What's the difference?

**Comment by madki** [comment]
I should probably remove that repo. Bundler is freighter after many many improvements. I just migrated the repo from 'Freighter' to 'Bundler' for reasons I don't remember now. Sorry for the confusion

**Comment by Rainer-Lang** [comment]
@madki Maybe you should write in freighter readme "deprecated -> use bundler <link>"
Anyway, thanks for clarification.
